[package]
name = "lacker"
version = "0.4.0"
edition = "2021"

[dependencies]
gtk4 = "0.9"
gtk4-layer-shell = {version = "0.4", optional = true}
freedesktop-desktop-entry = "0.5"
chrono = "0.4"
zbus = "4.0"
futures = "0.3"
tokio = { version = "1", features = ["rt", "macros"] }
urlencoding = "2.1"

[features]
default = []
wayland = ["gtk4-layer-shell"]
